# Generated by Django 3.2.8 on 2021-10-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='photo',
            new_name='photos',
        ),
    ]
