# Generated by Django 3.2.8 on 2021-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_photo_team_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photos',
            field=models.ImageField(upload_to='photo/%Y/%M/%D'),
        ),
    ]
