# Generated by Django 3.2.8 on 2021-11-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_team_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photos',
            field=models.ImageField(upload_to='../photo/%Y/%m/%d'),
        ),
    ]
