# Generated by Django 3.2.8 on 2021-11-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(max_length=200)),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(max_length=200)),
                ('body_design', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('model_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)])),
                ('is_featured', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('main_photo', models.ImageField(upload_to='../photos/%Y/%m/%d')),
                ('temp_photo_1', models.ImageField(upload_to='../photos/%Y/%m/%d')),
                ('temp_photo_2', models.ImageField(upload_to='../photos/%Y/%m/%d')),
                ('temp_photo_3', models.ImageField(upload_to='../photos/%Y/%m/%d')),
                ('passengers', models.IntegerField()),
                ('VIN', models.CharField(max_length=50)),
                ('no_of_previous_owners', models.IntegerField()),
                ('interior', models.CharField(max_length=100)),
                ('no_of_doors', models.IntegerField()),
                ('condition', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
