# Generated by Django 3.2.8 on 2021-11-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_model_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='no_of_doors',
            new_name='doors',
        ),
    ]
