# Generated by Django 3.2.8 on 2021-11-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_no_of_doors_car_doors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='doors',
            new_name='car_doors',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='interior',
            new_name='car_interior',
        ),
    ]
