# Generated by Django 3.2.8 on 2021-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211107_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=200),
        ),
    ]
