# Generated by Django 3.2.8 on 2021-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_car_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
