# Generated by Django 3.2.8 on 2021-11-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='features',
            new_name='car_features',
        ),
    ]
