# Generated by Django 3.2.8 on 2021-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='temp_photo_4',
            field=models.ImageField(blank=True, upload_to='../photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='car',
            name='temp_photo_1',
            field=models.ImageField(blank=True, upload_to='../photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='car',
            name='temp_photo_2',
            field=models.ImageField(blank=True, upload_to='../photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='car',
            name='temp_photo_3',
            field=models.ImageField(blank=True, upload_to='../photos/%Y/%m/%d'),
        ),
    ]
